name: feature_folder_cli
description: >-
  CLI utility that generates a folder structure to reduce the repetitive work
  required to setup directories for models, services, repositories, screens and
  widgets.
version: 0.3.0
homepage: https://github.com/RyanDsilva/feature_folder_cli

documentation: https://github.com/RyanDsilva/feature_folder_cli#folder-by-feature-cli-utility

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  ansicolor: ^2.0.2
  args: ^2.5.0
  mason: ^0.1.0-dev.53 
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.5

executables:
  ff: main
